### ISSUE TITLE
Basic Authentication scheme uses two requests

### ISSUE THREAD

**Issue by caged** [lukeredpath/LRResty#1]
Hi,

I'm using basic auth and it looks like LRResty isn't sending this information as a base64 encoded header, but rather it's waiting for one request to receive an authentication challenge and then sending another request with the credentials.

It looks like I might be able to get around this by supplying my own base64 routine and using attachRequestModifier.  I think the header approach is much better as it is technically faster and less stress on your server (one request vs two).

I used the Auth header in HTTPRiot and this is also the approach that ASIHTTPRequest has taken.  Are there any benefits to the current implementation?

**Comment by lukeredpath** [comment]
I agree and I think I will update Resty to do the same. 

I do think there is a case for making use of the authentication challenge header and that is when you don't know the authentication details up front; in this case I think it Ames sense to wait for the authentication challenge and respond to it (presumably by presenting a login UI). 

This scenario is probably best handled with a separate delegate method or callback.

**Comment by lukeredpath** [comment]
By default, set the Authorization header when using HTTP Basic authentication. Closed by 1386901f9d8c63587c5a36badf997df12aa0961f.
