### ISSUE TITLE
Access Denied when downloading LRResty-iOS-0.10.dmg

### ISSUE THREAD

**Issue by osuritz** [lukeredpath/LRResty#12]
When trying to download LRResty-iOS-0.10.dmg (i.e. NOT the nightly iOS build), we get an access denied error:

<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>061052C0AD5B6E1D</RequestId>
  <HostId>zXZUL+6Hd3BnIXVrXWR9HWOzqtSQtkoT0Yefxxo3N8Gd9bbSYBNitkhkitQaUB+u</HostId>
</Error>

**Comment by mattlanham** [comment]
Yup i got the same error

**Comment by pbihler** [comment]
Yes, very annoying - can you fix this?

**Comment by lukeredpath** [comment]
Not sure what was wrong with the download but I've removed it now. I recommend using the nightly build.
