### ISSUE TITLE
Digest authentication...

### ISSUE THREAD

**Issue by mflint** [lukeredpath/LRResty#14]
Any plans to support Digest authentication in LRResty?

:)

  Matthew

**Comment by mflint** [comment]
Reason for asking: I'm happy to fork and submit a pull request, but wanted to check first that it's not something already being worked on, and that you'd be happy to receive a pull request in principle :)

**Comment by mflint** [comment]
<embarrassed>Of course it works already. I'm just being dim.</embarrassed>

**Comment by lukeredpath** [comment]
I'd happily accept a patch…(with tests)
