### ISSUE TITLE
Block never invoked if failure happens before response received

### ISSUE THREAD

**Issue by caged** [lukeredpath/LRResty#2]
If a failure happens before a response is received, the block is never invoked.  This happens in cases where the remote server is down.

**Comment by lukeredpath** [comment]
I think the best way of handling this would be to allow the configuration of an error handler block that is used for all requests. It seems unlikely that you would want to handle connection errors like this differently for each request. 

Error handling needs improving in general so this is something I will look carefully at.

**Comment by lukeredpath** [comment]
I've made a start on error handling via a block or the delegate in a separate branch:
http://github.com/lukeredpath/LRResty/tree/error_handling

**Comment by kluivers** [comment]
I found that the completion block also doesn't get called when using https. I tried the same resource on http and https. Plain http worked, https did not work. Anything that needs to be done to request a https resource?

**Comment by ir-fuel** [comment]
Any news on this? It is very annoying not to be able to handle a connection failure in the response block somehow. Now the app just 'hangs' waiting for something to come back from the HTTP request.

Thanks for this nice http framework btw!

**Comment by caged** [comment]
From the grave!  Doing some cleanup of old issues.
