### ISSUE TITLE
Example - missing files

### ISSUE THREAD

**Issue by 1am** [lukeredpath/LRResty#21]
Hi
While trying to compile the provided example code I'm getting an:

> ExamplesViewController.m:11:9: fatal error: 'GithubCredentials.h' file not found

And indeed the "GithubCredentials.h" and "TwitterCredentials.h" files are missing. I cloned the example from the master branch.

**Comment by lukeredpath** [comment]
You need to create these files yourself. An example file is provided:

https://github.com/lukeredpath/LRResty/blob/master/Resources/GithubCredentials.h.example
