### ISSUE TITLE
Add ability to handle errors in callbacks.

### ISSUE THREAD

**Issue by caged** [lukeredpath/LRResty#3]
I assumed I would be able to handle errors in the callback.  So, my callback might look something like what you see below.

```
[self.client get:resource withBlock:^(LRRestyResponse *response) {
    if(response.error) {
         // Failed for some reason
    } else {
      // Response was in the 200 range
    }
}];
```

The workaround for this is that I need to check the status code in every callback to determine if the request was a success or not.  If the status isn't in the success range, I'd need to call [NSHTTPURLResponse localizedStringForStatusCode:[response status]] to fetch the reason.

**Comment by lukeredpath** [comment]
I made a decision to not do any smart response code handling, preferring to let the user handle this according to their own application logic. I also want to keep the idea of an error (as returned by NSURLConnection at any stage) and a non-success HTTP status as two distinct concepts. 

One enhancement would be to add some helpers to the Response object to encapsulate some common tasks like there being a 2xx code (wasSuccess) and a localised status message that encapsulates the snippet mentioned above.

**Comment by caged** [comment]
From the grave!  Doing some cleanup of old issues.
