### ISSUE TITLE
Form encoded requests strip NSNumber values

### ISSUE THREAD

**Issue by caged** [lukeredpath/LRResty#4]
I haven't fully tested this, so it might apply to anything that inherits from NSValue or any non-retained, non-copied value.  If you send a post request with an NSNumber in the payload, it's stripped, but the request will still complete.  If I convert the number to a string before sending it to post:payload:withBlock, everything works as expected.

**Comment by lukeredpath** [comment]
Non-string objects should have their description form-encoded when part of a payload. Closed by 393864109ff24efae82b6aa7f24692eb2ea98d88.

**Comment by caged** [comment]
That was quick! :D
