### ISSUE TITLE
Add ability to cancel Request

### ISSUE THREAD

**Issue by NukemHill** [lukeredpath/LRResty#5]
I need the ability to cancel an upload or download on command.  It looks (in my five minute perusal of the source) like it can be done by accessing the instance of NSOperationQueue residing inside of LRRestyHTTPClient.  operationQueue is handed an instance of LRRestyRequest.

Two questions:
1)  It seems simple enough to just tack "cancel" methods onto LRRestyClient and LRRestyHTTPClient, so that a cancel message can be handed off to operationQueue.  Is that the best way to do this?
2)  "cancelAllOperations" is the method call on NSOperationQueue.  That will then pass on a cancel message to the instance of LRRestyRequest.  Will LRRestyRequest be smart enough to handle this?  If not, what additional work needs to be done in LRRestyRequest to handle the cancel message?

In further analysis, I see that LRRestyRequest is a child of LRURLRequestOperation, which is in turn a child of NSOperation.  NSOperation has a cancel method (which is what is being called by [NSOperationQueue cancelAllOperations].  Does that intrinsically cancel everything in any of its children classes, or do I have to override it and explicitly make a call to [NSURLConnection cancel]?

I fully admit that I don't have a deep understanding of how NSOperation and NSOperationQueue work.  So I apologize if I'm asking nonsensical questions.  I'd just like to see how to implement this in a way that allows me to cancel a connection gracefully on command.

Any suggestions are gratefully accepted.  Thank you.

**Comment by lukeredpath** [comment]
There should be no need to access the queue directly. As you rightly point out, you can just keep a pointer to the LRRestyRequest returned by any of the request methods and call `cancel` on it. It is the super-class of LRRestyRequest, LRURLRequestOperation that handles cancellation.

If you look at the source of `LRURLRequestOperation` you will see that all calling "cancel" does is set a flag. It's down to the implementation of your operation to periodically check this flag and handle it accordingly, which is what `LRURLRequestOperation` does.

It does sound like having a method to cancel all outstanding operations would be useful though.
