### ISSUE TITLE
Building framework in Xcode 4

### ISSUE THREAD

**Issue by NukemHill** [lukeredpath/LRResty#6]
Okay, I'm feeling particularly stupid at this point.  I've not dealt with frameworks in Xcode 4 (nor, hardly, in Xcode 3.x, for that matter), and I'm hitting a wall.  I've been digging around in the docs, and starting to get a feel for Schemes.  But I can't seem to get to the point where I've got a build result that gives me an LRResty.framework folder with all of the necessary components residing inside.

I don't really know/understand what is happening, so I'm pretty much stuck at this point.  Has anyone here built LRResty in Xcode 4?  Any thoughts or tips on what I should be doing?  I've googled extensively, and I've not seen anything from anyone about building frameworks in Xcode 4.  Lots about including pre-built ones.  But nothing about starting from scratch.

Help!

**Comment by lukeredpath** [comment]
Hi there, have you tried using the Rake tasks provided?

**Comment by NukemHill** [comment]
Just getting back to this after being swamped with other priorities.  Luke, which tasks are you referring to?  I don't know what Rake is.  Where do I find what you're talking about?

Thanks for getting back to me.  I'd like to learn this process.  The more skills I have, the easier the process becomes....

**Comment by lukeredpath** [comment]
Rake is a tool written in the Ruby programming language and is a bit like Make. It's a tool for building projects or running tasks on the command line.

As a Ruby developer, I like to use this to automate tasks on my Objective-C projects too. Most Macs already have a Ruby and Rake installation (try running `rake` on the command line).

Instructions for building from source are available here:
http://projects.lukeredpath.co.uk/resty/getting-started.html

If you're still having trouble, you can download the latest version of Resty from the "Downloads" section on the Github project page. Alternatively, you can grab an automated nightly build from [here](http://projects.lukeredpath.co.uk/resty/downloads/).
