### ISSUE TITLE
problem linking to libLRResty.a in iOS project (Xcode 4.0.2)

### ISSUE THREAD

**Issue by jmoody** [lukeredpath/LRResty#7]
I've used LRResty in a Cocoa application as a framework (LRResty.framework) and I was very pleased.

I would like to use libLRResty.a in an iOS project, but I am having trouble. 

I used the rake tool to build a combined ios/iosimulator library, but made one change to the Rakefile:

```
  BASE_SDK = 4.3
```

```
  %  rake buid:clean
  %  rake build:combined
```

The build appears to work.  There is one issue around the CodePilot 2.0 plugin (I am a beta tester).   I don't really think this is an issue, but it might be, so I include the output below.

I am use a number of static libraries and am familiar with how to include them in my targets.  In this particular case, I am also linking libOCMock.a without any difficulties.

Can you confirm that I used the correct rake command for building for iOS (device and simulator)?

I am using the following import statement:

```
 #import <LRResty/LRResty.h>
```

(Xcode actually suggests this as a completion)

When I build (for device or simulator) I get: LRResty/LRResty.h: No such file or directory.

Any suggestions? 

Thanks,

jmoody

=== BEGIN CODE PILOT ISSUE ===

WARNING: skipping plug-in at path '/Users/moody/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CodePilot.xcplugin' because it is not compatible with this version of Xcode.
2011-04-28 17:44:05.190 xcodebuild[74612:80f] Error loading /Users/moody/Library/Developer/Xcode/Third-Party Plug-ins/CodePilot2.xcplugin/Contents/MacOS/CodePilot2:  dlopen(/Users/moody/Library/Developer/Xcode/Third-Party Plug-ins/CodePilot2.xcplugin/Contents/MacOS/CodePilot2, 265): Symbol not found: _OBJC_CLASS_$_IDEDocumentController
  Referenced from: /Users/moody/Library/Developer/Xcode/Third-Party Plug-ins/CodePilot2.xcplugin/Contents/MacOS/CodePilot2
  Expected in: flat namespace
 in /Users/moody/Library/Developer/Xcode/Third-Party Plug-ins/CodePilot2.xcplugin/Contents/MacOS/CodePilot2
2011-04-28 17:44:05.190 xcodebuild[74612:80f] WARNING: Failed to load plugin at: /Users/moody/Library/Developer/Xcode/Third-Party Plug-ins/CodePilot2.xcplugin, skipping.  Could not load bundle

=== END CODE PILOT ISSUE ===

**Comment by lukeredpath** [comment]
Sorry for not replying to this earlier.

The rake task you want to run is `build:ios:framework`.

This will build a static framework which looks like an ordinary Mac framework but uses a static library so it can be used on iOS. The import should then work correctly.
