### ISSUE TITLE
no DELETE

### ISSUE THREAD

**Issue by maddox** [lukeredpath/LRResty#8]
is there any particular reason theres no delete method?

**Comment by lukeredpath** [comment]
Never got round to it. Don't know why. It should be a simple addition, would you care to submit a patch? (I'm busy with my newborn daughter at the moment!)

**Comment by maddox** [comment]
yeah i mostly likely will. Keep a look out.

**Comment by lukeredpath** [comment]
This has now been added.

**Comment by maddox** [comment]
I saw! Awesome. thanks! Lots of work the last week or so. 

I added it myself, but between all the tests and getting it to build all the different ways + me using xcode 4, it was a shit ton of stuff to figure OUT before actually getting shit done, so I never sent a pull request. Sorry, lol.

thanks.

**Comment by lukeredpath** [comment]
No worries, I've spent quite a bit of time myself over the last few days fighting Xcode 4 but the project should now build properly in Xcode 4. I've also figured out a way to get the tests running in Xcode 4 too.

Automated builds are also now available:
http://projects.lukeredpath.co.uk/resty/downloads
